### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by luke-pritch**

### CODE REVIEW

**Comment by zwzn** [comment]
Do you want to make the login page under the home page? It is styled almost exactly the same. If not we should break the bar out into its own component so that we don't need to duplicate it

**Comment by zwzn** [comment]
When you click the email login button it takes a bit of time to pop up, can you add a loading spinner

**Comment by luke-pritch** [comment]
>  When you click the email login button it takes a bit of time to pop up, can you add a loading spinner
>  Can you add a back button to go from the email login section back to the 3 buttons

Yeah so the drop FirebaseUI isn't really designed to be more customized beyond simple styling or else it is liable to break upon an update. See here for the issue relating to it here: https://github.com/firebase/FirebaseUI-Android/issues/1383

**Comment by zwzn** [comment]
* [ ] Change the login/sign up buttons to sign out buttons when logged in.
  * Look into 
[firebase.auth().onAuthStateChanged()](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onauthstatechanged)
and
[firebase.auth().currentUser](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#currentuser)
  * `useUser` would be a useful hook that could put these together

**Pull request merged**
